name: Antlir Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: centos:centos8

    steps:
      - name: Install system dependencies
        run: |
          yum update -y
          yum groupinstall "Development Tools" -y
          yum install -y \
            java-11-openjdk \
            systemd-container \
            libcap-ng-devel
          java --version

      # https://github.com/sclorg/s2i-python-container/blob/master/3.9/Dockerfile.rhel8
      - name: Install Python
        run: |
          INSTALL_PKGS="python39 python39-devel python39-setuptools python39-pip nss_wrapper \
            httpd httpd-devel mod_ssl mod_auth_gssapi mod_ldap \
            mod_session atlas-devel gcc-gfortran libffi-devel libtool-ltdl enchant"
          yum -y module enable python39:3.9 httpd:2.4
          yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS
          rpm -V $INSTALL_PKGS
          ln -fs /usr/bin/python3.9 /usr/bin/python
          python --version

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up $PATH
        run: echo $(pwd)/tools > $GITHUB_PATH

      - name: Fetch buck
        run: buck --version

      # Make it very clear if a failure is due to the target graph being
      # unparseable, or an actual build failure.
      - name: Validate target graph
        run: buck targets //...

      - name: Fetch remote artifacts
        run: buck fetch //...

      # This is not quite a test, but exercises a lot of antlir and is expected
      # to pass, unlike the unit tests below, not all of which have been fixed
      # to support the OSS build (mainly due to missing 'yum')
      - name: Build base image(s)
        run: buck build //images/base/...

      - name: Run cxx tests
        # TODO(vmagro): cxx_tests are excluded from 'buck test' because the
        # test runner assumes that test output ends up in a certain spot on the
        # host, and we have so few of these it doesn't make sense to invest in
        # fixing our wrappers for both internal and external use for right now.
        run: buck query 'kind(cxx_test, //...)' | xargs -n1 buck run
        continue-on-error: true

      - name: Run tests
        # Run all tests, excluding any that are disabled (mainly the hidden
        # layer tests)
        # TODO(vmagro): cxx_test is excluded because the Buck test runner
        # assumes that test output ends up in a certain spot on the host.
        # TODO(vmagro): re-enable vm tests soon, right now they are
        # known-broken due to some missing infra.
        # TODO(lsalis): re-enable locale tests when there is a working
        # alternative to build-locale-archive for fedora
        # WARNING: keep this query in sync with the internal one in antlir.td
        # to ensure the same set of tests is run internally and externally
        run: |
          buck test --always-exclude $(buck query @tools/ci_tests_query) --xml tests.xml > buck.log 2> buck.err || true
          echo Buck stderr
          cat buck.err
          echo Test results
          ./tools/results_parser.py tests.xml
